- name: Install Helm
  shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Add Helm repo
  shell: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo update
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Create monitoring namespace
  command: kubectl create namespace monitoring
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: monitoring_namespace
  failed_when: monitoring_namespace.rc != 0 and 'AlreadyExists' not in monitoring_namespace.stderr
  changed_when: monitoring_namespace.rc == 0

- name: Install Prometheus + Grafana stack
  shell: |
    helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
      --namespace monitoring \
      --create-namespace
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
