- name: Update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

- name: Install basic packages
  apt:
    name:
      - python3-bcrypt
      - python3-pip 
      - curl
      - git
      - vim
      - unzip
      - htop
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
  become: yes