- name: Create argocd namespace
  shell: kubectl create namespace argocd || true

- name: Install ArgoCD
  shell: |
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Wait for ArgoCD server to be ready
  shell: kubectl rollout status deployment argocd-server -n argocd